# Generated by Django 2.0b1 on 2019-01-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190127_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Changes',
            new_name='games',
        ),
    ]
