# Generated by Django 2.0b1 on 2019-01-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190127_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='gamesLocation',
        ),
    ]
