# Generated by Django 2.0b1 on 2019-06-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gameslocation',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
