# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20190625_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
