# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gameslocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[games.validators.validate_category]),
        ),
    ]
