# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-02 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gameslocation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameslocation',
            name='owner',
        ),
    ]
