# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-05 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamelists1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='game',
            new_name='newgame',
        ),
    ]
