# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-05 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gameslocation_owner'),
        ('Gamelists1', '0003_remove_item_newgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='newgame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.gamesLocation'),
            preserve_default=False,
        ),
    ]
