# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-06 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamelists1', '0004_item_newgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='newgame',
            new_name='GameResemblance',
        ),
    ]
