# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-06 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamelists1', '0005_auto_20190706_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='GameResemblance',
        ),
    ]
