# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gameslocation_owner'),
        ('Gamelists1', '0008_remove_item_gamedangler'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Gamegangler',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='games.gamesLocation'),
            preserve_default=False,
        ),
    ]
